name: Test
on:
  push:
    branches:
      - develop
      - feature
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        if: github.event_name == 'push'
        run: |
          GITHUB_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo "DOMAIN_NAME=$(echo $GITHUB_BRANCH_NAME)" >> $GITHUB_ENV
      - name: Get pull request number
        if: github.event_name == 'pull_request'
        run: |
          GITHUB_PULL_REQUEST_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "DOMAIN_NAME=pr-$(echo $GITHUB_PULL_REQUEST_NUMBER)" >> $GITHUB_ENV
      - name: Debug
        run: echo ${{ env.DOMAIN_NAME }} 
